spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/todolist"
    username: "root"
    password: "11wjdghd"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      encoding: utf-8
server:
  port: 8080